# EDA on IOT BASE DATA

## â€¢	Data Ingestion Module:- Reads sensor data and threshold data from CSV files.

In [3]:
import pandas as pd

In [62]:
# loding Sensotr CSV Data file
sensor_df = pd.read_csv('Downloads/sensor_data.csv')

In [63]:
# loding Threshold CSV data file
threshold_df = pd.read_csv('Downloads/thresholds.csv')

In [16]:
sensor_df.head(20)

                   date sensor_type    value   unit  location_id    month
0   2024-01-11 00:00:00    pressure  1031.58    hPa        106.0  2024-01
1   2023-11-01 00:00:00    pressure   990.08    hPa        109.0  2023-11
2   2023-10-08 00:00:00       light   656.83    lux        102.0  2023-10
3   2023-08-28 00:00:00    pressure   994.60    hPa        103.0  2023-08
4   2023-10-07 00:00:00    pressure   961.35    hPa        102.0  2023-10
5   2023-08-11 00:00:00    humidity    70.06      %        109.0  2023-08
6   2023-09-12 00:00:00    pressure   956.30    hPa        109.0  2023-09
7   2023-10-12 00:00:00    pressure  1042.35    hPa        110.0  2023-10
8   2023-10-02 00:00:00    pressure  1040.98    hPa        106.0  2023-10
9   2023-08-24 00:00:00    pressure  1026.14    hPa        105.0  2023-08
10  2023-08-08 00:00:00    pressure  1035.52    hPa        103.0  2023-08
11  2023-11-07 00:00:00      motion    27.00  count        103.0  2023-11
12  2024-01-17 00:00:00       light     1.20    lux        102.0  2024-01
13  2023-08-31 00:00:00       sound    48.74     dB        103.0  2023-08
14  2023-10-16 00:00:00    humidity    61.11      %        108.0  2023-10
15  2023-09-07 00:00:00    pressure   958.04    hPa        110.0  2023-09
16  2023-09-12 00:00:00    humidity    66.05      %        105.0  2023-09
17  2023-10-12 00:00:00    humidity    68.38      %        103.0  2023-10
18  2024-01-31 00:00:00    humidity    80.90      %        101.0  2024-01
19  2023-09-05 00:00:00       sound    45.57     dB        106.0  2023-09

In [12]:
threshold_df.head(15) # the cse file contains only 7 feelds

   sensor_type  min_threshold  max_threshold
0  temperature             15             35
1     humidity             40             80
2     pressure            960           1040
3          co2            350            700
4          voc            150            450
5        light            100            900
6        sound             30            100
7       motion              5             30

In [43]:
sensor_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10004 entries, 0 to 10003
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         10004 non-null  object
 1   sensor_type  10004 non-null  object
 2   value        10003 non-null  float64
 3   unit         10004 non-null  object
 4   location_id  10003 non-null  float64
 5   month        10000 non-null  object
dtypes: float64(2), object(4)
memory usage: 469.1+ KB

In [15]:
sensor_df['sensor_type'].describe()

count        10004
unique           9
top       pressure
freq          1290
Name: sensor_type, dtype: object

In [38]:
# Cleaning the time HH:MM:SS in the data

sensor_data = sensor_df['date'] = sensor_df['date'].astype(str).str.split(' ').str[0]

In [44]:
sensor_df.head()

         date sensor_type    value unit  location_id    month
0  2024-01-11    pressure  1031.58  hPa        106.0  2024-01
1  2023-11-01    pressure   990.08  hPa        109.0  2023-11
2  2023-10-08       light   656.83  lux        102.0  2023-10
3  2023-08-28    pressure   994.60  hPa        103.0  2023-08
4  2023-10-07    pressure   961.35  hPa        102.0  2023-10

In [45]:
sensor_df['sensor_type'].unique()

array(['pressure', 'light', 'humidity', 'motion', 'sound', 'co2',
       'temperature', 'voc', 'invalid_sensor'], dtype=object)

In [55]:
sensor_group = sensor_df.groupby(['sensor_type'])
sensor_group.get_group('pressure')

C:\Users\AkhilPokuri\AppData\Local\Temp\ipykernel_6580\2115909858.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sensor_group.get_group('pressure')

             date sensor_type    value unit  location_id    month
0      2024-01-11    pressure  1031.58  hPa        106.0  2024-01
1      2023-11-01    pressure   990.08  hPa        109.0  2023-11
3      2023-08-28    pressure   994.60  hPa        103.0  2023-08
4      2023-10-07    pressure   961.35  hPa        102.0  2023-10
6      2023-09-12    pressure   956.30  hPa        109.0  2023-09
...           ...         ...      ...  ...          ...      ...
9974   2023-09-21    pressure   979.29  hPa        105.0  2023-09
9976   2023-09-17    pressure  1018.21  hPa        101.0  2023-09
9981   2023-09-11    pressure   972.53  hPa        106.0  2023-09
9994   2023-12-19    pressure  1015.46  hPa        109.0  2023-12
10003  2024-02-17    pressure   980.00  hPa          NaN      NaN

[1290 rows x 6 columns]

In [50]:
sensor_df['sensor_type'].value_counts()

sensor_type
pressure          1290
temperature       1271
voc               1263
humidity          1262
co2               1237
light             1232
sound             1225
motion            1223
invalid_sensor       1
Name: count, dtype: int64

In [56]:
sensor_df.head()

         date sensor_type    value unit  location_id    month
0  2024-01-11    pressure  1031.58  hPa        106.0  2024-01
1  2023-11-01    pressure   990.08  hPa        109.0  2023-11
2  2023-10-08       light   656.83  lux        102.0  2023-10
3  2023-08-28    pressure   994.60  hPa        103.0  2023-08
4  2023-10-07    pressure   961.35  hPa        102.0  2023-10

In [57]:
monthly_stats = sensor_df.groupby(['month', 'sensor_type'])['value'].agg(['mean', 'max', 'min']).reset_index()

In [75]:
monthly_stats.head(40)

      month  sensor_type    avg_value  min_value  max_value
0   2023-08          co2   550.315156     301.28     799.12
1   2023-08     humidity    60.369632      30.19      89.87
2   2023-08        light   535.739330       0.04     998.97
3   2023-08       motion    26.353982       0.00      50.00
4   2023-08     pressure   999.317149     950.24    1049.62
5   2023-08        sound    65.007350      20.25     117.86
6   2023-08  temperature    23.966682      10.06      39.88
7   2023-08          voc   299.715111     104.25     499.52
8   2023-09          co2   557.989490     303.45     797.80
9   2023-09     humidity    59.486404      30.04      89.84
10  2023-09        light   489.539851       6.65     991.55
11  2023-09       motion    24.483871       0.00      50.00
12  2023-09     pressure   998.008811     950.40    1049.77
13  2023-09        sound    70.285590      20.11     119.32
14  2023-09  temperature    24.993384      10.42      39.76
15  2023-09          voc   304.180091     100.15     496.90
16  2023-10          co2   542.442269     301.30     793.95
17  2023-10     humidity    60.408294      30.04      89.98
18  2023-10        light   506.880529       8.84     994.45
19  2023-10       motion    24.377990       0.00      50.00
20  2023-10     pressure  1003.152222     950.08    1049.90
21  2023-10        sound    68.821990      20.25     119.83
22  2023-10  temperature    25.522454      10.19      39.73
23  2023-10          voc   293.635349     105.97     497.79
24  2023-11          co2   536.832905     300.91     799.26
25  2023-11     humidity    60.507641      30.08      89.89
26  2023-11        light   520.777079      13.23     997.03
27  2023-11       motion    23.567568       0.00      50.00
28  2023-11     pressure  1002.410800     950.55    1049.97
29  2023-11        sound    68.621414      20.10     119.44
30  2023-11  temperature    25.046154      10.02      39.95
31  2023-11          voc   315.043462     102.42     497.73
32  2023-12          co2   527.915931     302.45     797.45
33  2023-12     humidity    58.707343      30.13      89.78
34  2023-12        light   502.580236       3.92     995.72
35  2023-12       motion    24.088670       0.00      50.00
36  2023-12     pressure   996.983757     950.23    1048.33
37  2023-12        sound    68.892735      20.45     119.24
38  2023-12  temperature    25.663568      10.43      39.82
39  2023-12          voc   291.149511     101.84     496.18

In [89]:
# saving the date in a CSV  "month"	"sensor_type"	"avg_value"	 "min_value"	"max_value"
save_path = "C:\\Users\\AkhilPokuri\\monthly_stats.csv"  
monthly_stats.to_csv(save_path, index=True)

In [85]:
sensor_name = 'temperature'  # sensor type
max_value = sensor_df.loc[sensor_df['sensor_type'] == sensor_name, 'value'].max()
print(max_value)

39.97

In [83]:
sensor_name = 'temperature'  # sensor type
max_value = sensor_df.loc[sensor_df['sensor_type'] == sensor_name, 'value'].min()
print(max_value)

10.02

In [84]:
sensor_name = 'co2'  # sensor type
max_value = sensor_df.loc[sensor_df['sensor_type'] == sensor_name, 'value'].max()
print(max_value)

799.26

In [92]:
sensor_name = 'co2'  # sensor type
max_value = sensor_df.loc[sensor_df['sensor_type'] == sensor_name, 'value'].mean()
print(max_value)

545.7511156022636